baseURL = "https://deg117.github.io/pagina-hugo/"
languageCode = "es-mx"
title = "Portafolio de Brian"
theme = "ananke"

[params]
  site_logo = ""
  description = "Estudiante de Ibgenieria en Software — Portafolio personal"
  featured_image = "images/galaxy.jpg"
  background_color_class = "bg-transparent"