baseURL = "https://deg117.github.io/pagina-hugo/"
languageCode = "es-mx"
title = "Portafolio de Brian"
theme = "ananke"

[params]
  site_logo = ""
  description = "Estudiante de Ingeniería en Software — Portafolio personal"

  # Color de fondo del hero (elige el que quieras)
  background_color_class = "bg-dark-blue"
